---
- name: update and upgrade packages.
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: install pm2
  become: yes
  shell: |
    apt update && apt install sudo curl && curl -sL https://raw.githubusercontent.com/Unitech/pm2/master/packager/setup.deb.sh | sudo -E bash -

- name: install node_exporter
  become: yes
  shell: |
    sudo useradd --no-create-home node_exporter
    wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    tar xzf node_exporter-1.0.1.linux-amd64.tar.gz
    sudo cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
    rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64

- name: Configure node-exporter service
  become: yes
  shell: |
    echo "
    [Unit]
    Description=Prometheus Node Exporter Service
    After=network.target

    [Service]
    User=node_exporter
    Group=node_exporter
    Type=simple
    ExecStart=/usr/local/bin/node_exporter

    [Install]
    WantedBy=multi-user.target" > /etc/systemd/system/node-exporter.service

- name: extract artifact
  become: yes
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: .

- name: Configure systemd
  shell: |
    sudo systemctl daemon-reload
    sudo systemctl enable node-exporter
    sudo systemctl start node-exporter
    sudo systemctl status node-exporter

- name: start app
  become: yes
  shell: |
    cd ~/dist
    touch .env
    echo ENVIRONMENT=production > ".env"
    echo TYPEORM_CONNECTION=postgres >> ".env"
    echo TYPEORM_ENTITIES=./src/modules/domain/*/.entity.ts >> ".env"
    echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> ".env"
    echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> ".env"
    echo NODE_ENV=production >> ".env"
    echo TYPEORM_HOST=uda-people.cscd3kjezvqg.us-east-1.rds.amazonaws.com >> ".env"
    echo TYPEORM_PORT=5432 >> ".env"
    echo TYPEORM_USERNAME=postgres >> ".env"
    echo TYPEORM_PASSWORD=udapeople1234 >> ".env"
    echo TYPEORM_DATABASE=postgres >> ".env"
    sudo apt-get install -y nodejs
    npm install -g npm@latest
    npm install -g webpack-dev-server
    npm install
    npm run build
    pm2 stop default
    pm2 start npm --name backend -- start