# ---
# - name: update and upgrade packages.
#   become: yes
#   apt:
#     upgrade: yes
#     update_cache: yes

# - name: install pm2
#   become: yes
#   shell: |
#     apt update && apt install sudo curl && curl -sL https://raw.githubusercontent.com/Unitech/pm2/master/packager/setup.deb.sh | sudo -E bash -

# - name: install node_exporter
#   become: yes
#   shell: |
#     sudo useradd --no-create-home node_exporter
#     wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
#     tar xzf node_exporter-1.0.1.linux-amd64.tar.gz
#     sudo cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
#     rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64

# - name: Configure node-exporter service
#   become: yes
#   shell: |
#     echo "
#     [Unit]
#     Description=Prometheus Node Exporter Service
#     After=network.target

#     [Service]
#     User=node_exporter
#     Group=node_exporter
#     Type=simple
#     ExecStart=/usr/local/bin/node_exporter

#     [Install]
#     WantedBy=multi-user.target" > /etc/systemd/system/node-exporter.service

# - name: Configure systemd
#   shell: |
#     sudo systemctl daemon-reload
#     sudo systemctl enable node-exporter
#     sudo systemctl start node-exporter
#     sudo systemctl status node-exporter

# - name: start app
#   become: yes
#   shell: |
#     cd ~/dist
#     npm install -g npm@latest
#     npm install -g webpack-dev-server
#     npm install
#     npm run build
#     pm2 stop default
#     pm2 start npm --name backend -- start

---
- name: update and upgrade packages.
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: remove unneeded deps
  become: yes
  apt:
    autoremove: yes

- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes

- name: extract artifact
  become: yes
  unarchive:
    src: ~/project/backend_artifact.tar.gz
    dest: .

- name: start app
  become: yes
  shell: |
    cd ~/dist
    npm install -g npm@latest
    npm install -g webpack-dev-server
    npm install
    npm run build
    pm2 start npm --name backend -- start