---
- name: update and upgrade packages.
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: remove unneeded deps
  become: yes
  apt:
    autoremove: yes

- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes

- name: extract artifact
  become: yes
  unarchive:
    src: ~/project/backend_artifact.tar.gz
    dest: .

- name: start app
  become: yes
  shell: |
    cd ~/dist
    npm install -g npm@latest
    npm install -g webpack-dev-server
    npm install
    npm run build
    pm2 start npm --name backend -- start