---
- name: update and upgrade packages.
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes

- name: install node_exporter
  become: yes
  shell: |
    sudo useradd --no-create-home node_exporter
    wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    tar xzf node_exporter-1.0.1.linux-amd64.tar.gz
    ./node_exporter-1.0.1.linux-amd64/node_exporter

- name: start app
  become: yes
  shell: |
    cd ~/dist
    npm install -g npm@latest
    npm install -g webpack-dev-server
    npm install
    npm run build
    pm2 stop default
    pm2 start npm --name backend -- start